cmp copy
guardian/csnx pull request #1128
Opened 2024-01-30 12:26 UTC by vlkerag

## What are you changing?

-

## Why?

-

2024-03-21 13:57 UTC, oliverabrahams commented on libs/@guardian/libs/cypress/support/e2e.js
> +import '../e2e/consent-management-platform/support/commands';
Do we want to have e2e.js and comands.js in separate directories

2024-03-21 13:59 UTC, oliverabrahams approved these changes
Looks good to me!

2024-03-25 10:14 UTC, akinsola-guardian approved these changes
Thanks for this. This looks good.

2024-03-25 15:33 UTC, sndrs commented on libs/@guardian/libs/src/index.ts
> +	Callback,
i think this name is a bit too generic for a library with many other exports - how about something like `OnConsentChangeCallback`?

2024-03-25 15:33 UTC, sndrs commented on libs/@guardian/libs/src/index.ts
> +	Framework,
this too is too generic - how about `ConsentFramework`?

2024-04-03 10:28 UTC, sndrs requested changes
we need to add a lint to https://github.com/guardian/consent-management-platform for the merge commit.

i'm on it, just hitting the red button to hold off merging till then

2024-04-03 16:20 UTC, sndrs commented on libs/@guardian/libs/src/index.ts
> +	Callback as OnConsentChangeCallback,
yeah agreed - but given you'll need to import from `libs` now, should that means a major version of `libs`?

2024-04-03 16:25 UTC, mxdvl commented on libs/@guardian/libs/src/index.ts
> +	Callback as OnConsentChangeCallback,
Oh yes, true! Carry on…

2024-04-04 09:37 UTC, sndrs approved these changes

2024-04-04 09:38 UTC, sndrs commented
will merge on monday morning, alongside https://github.com/guardian/consent-management-platform/pull/960

2024-04-08 09:10 UTC, merged