Update youtube overlay design
guardian/csnx pull request #653
Opened 2023-06-20 10:40 UTC by abeddow91

## What are you changing?

-

## Why?

-

2023-06-20 10:46 UTC, abeddow91 commented on libs/@guardian/atoms-rendering/src/YoutubeAtomOverlay.tsx
> -	neutral,
neutral is deprecated!

2023-06-20 10:47 UTC, abeddow91 commented on libs/@guardian/atoms-rendering/src/YoutubeAtomOverlay.tsx
> +import { SvgMediaControlsPlay } from '@guardian/source-react-components';
SvgPlay has been deprecated so this PR moves to the new SvgMediaControlsPlay 👍

2023-06-20 10:47 UTC, joecowton1 approved these changes

2023-06-23 07:01 UTC, joecowton1 requested changes
@abeddow91 @sophie-macmillan we're experiencing an issue with TS 5.1 and rollup which means the latest releases of source-react-components and source-react-components-development kitchen are broken.

We've a PR in progress to roll back to TS 4.9.5 which should be merged early next week - if you can hold off merging this until then everything should be working again. Apologies for the hold up!

2023-06-26 13:06 UTC, joecowton1 commented
@sophie-macmillan @abeddow91 the fix I was talking about is now on main, if you pull that into this branch everything should work again

2023-06-26 13:12 UTC, joecowton1 approved these changes

2023-06-27 08:51 UTC, abeddow91 commented on libs/@guardian/atoms-rendering/src/YoutubeAtomOverlay.tsx
> +	color: white;
```suggestion
	color: ${palette.neutral[100]};
```

2023-06-27 12:13 UTC, merged